- name: install openLDAP
  hosts: all
  become: true
  vars:
    ldap_domain: example.com
    ldap_organization: Example org.
    ldap_admin_password: password1
    ldap_base_dn: dc=example,dc=com

  tasks:
    - name: reconfigure slapd
      ansible.builtin.command:
       cmd: dpkg-reconfigure -f noninteractive slapd
      become: true
      register: slapd_reconfigure_ouput
    
    - name: show the result of the reconfigure command
      ansible.builtin.debug:
       msg: "{{ slapd_reconfigure_output.stdout }}"
