- name: Update package cache on all hosts
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      command: apt-get update
      when: ansible_facts['distribution'] in ['Ubuntu']
      tags:
        - update_cache
