- name: Update package cache on all hosts
  hosts: all
  become: true
  vars:
    ldap_domain: example.com
    ldap_organization: Example org.
    ldap_admin_password: securepassword
    ldap_base_dn: dc=example,dc=com

  tasks:
    - name: Update apt cache
      command: apt-get update
      when: ansible_facts['distribution'] in ['Ubuntu']
      tags:
        - update_cache

    - name: OpenLDAP prerequisites
      command: apt-get install -y ksh libtool-ltdl openssl perl lz4
      when: ansible_facts['distribution'] in ['Ubuntu']
      register: apt_install_result
      ignore_errors: true

    - name: check if package installation was successful
      fail:
        msg: "Failed to install required packages"
      when: apt_install_result.rc != 0
      tags:
        - install_openldap
