- hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: Install python3-apt
      apt:
        name:  python3-apt
        state: present
      become: yes
